platform :ios, '8.0'
# inhibit_all_warnings!

target 'VisionaryEdu' do
use_frameworks!
  pod 'SVProgressHUD'
  pod 'AFNetworking','~>3.1.0'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'RegExCategories'
  pod 'FSCalendar'
#   pod 'PNChart'
  pod 'JYRadarChart'
  pod 'FSLineChart'
  pod 'IQKeyboardManager'
end
